version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-challenge

  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh
    tty: true
    volumes:
      - ./node:/usr/src/app/
      - /usr/src/app/node_modules
    networks:
      - node-challenge
    depends_on:
      - db
    command: node index.js

  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - node-challenge

networks:
  node-challenge:
    driver: bridge
